### ISSUE TITLE
Weird behavior when encapsulating with % character

### ISSUE THREAD

**Issue by yooouuri** [dawnlabs/carbon#617]
**Describe the bug**
There are weird enters between the lines where percents are used (like the screenshot).

**To Reproduce**
1. Use the following code and set type to YAML
```yaml
pipelines:
  branches:
    production:
    - step:
        image: atlassian/pipelines-awscli
        caches:
        - docker
        script:
        - echo JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem >> .env
        - echo JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem >> .env
        services:
        - docker
```

2. Click on export as PNG

**Expected behavior**
There should be no enters between the lines. When I remove the lines with the percent, the format is fine.

**Screenshots**

Current behavior
![carbon 6](https://user-images.githubusercontent.com/12934957/50684158-d9254700-1014-11e9-9a59-46f5b27437a2.png)

Expected behavior
![carbon 7](https://user-images.githubusercontent.com/12934957/50684300-4802a000-1015-11e9-8092-bfb097b22e7a.png)

**Info (please complete the following information):**
 - OS [e.g. macOS, Linux, Windows, iOS]: Mac OS and Windows 10
 - Browser [e.g. chrome, safari]: Chrome
<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>
